use super::NetcodeError;
use crate::config::FullID;
use alloc::boxed::Box;
use firefly_hal::InputState;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub(crate) enum Message {
    Hello,
    /// Ask the device if it already started an app.
    ReqStart,
    /// Request the state for the given frame.
    ReqState(u32),
    /// Tell other devices that this device is going to disconnect.
    Disconnect,

    Intro(Intro),
    /// Launch an app.
    Start(Start),
    /// The app state sync, sent every frame when running an app.
    State(FrameState),
    /// Tell other devices that this device's user has accepted the peers' list.
    ///
    /// Inlcudes the number of peers.
    Ready(u8),
}

impl Message {
    // TODO: return NetworkError
    pub fn decode(s: &[u8]) -> Result<Self, NetcodeError> {
        if s.is_empty() {
            return Err(NetcodeError::EmptyBufferIn);
        }
        if s == b"HELLO" {
            return Ok(Self::Hello);
        }
        let res = postcard::from_bytes(s);
        match res {
            Ok(raw) => Ok(raw),
            Err(err) => Err(NetcodeError::Deserialize(err)),
        }
    }

    pub fn encode<'a>(&self, buf: &'a mut [u8]) -> Result<&'a mut [u8], NetcodeError> {
        let res = postcard::to_slice(self, buf);
        match res {
            Ok(raw) => {
                if raw.is_empty() {
                    Err(NetcodeError::EmptyBufferOut)
                } else {
                    Ok(raw)
                }
            }
            Err(err) => Err(NetcodeError::Serialize(err)),
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub(crate) struct Intro {
    /// The device name as stored in settings.
    pub name: heapless::String<16>,

    /// The runtime version.
    pub version: u16,

    /// The lowercase ASCII preferred device language.
    pub lang: [u8; 2],

    /// The uppercase ASCII country code.
    pub country: [u8; 2],

    /// The preferred color scheme.
    pub theme: u32,

    /// Packed bitflags for the following boolean settings:
    ///
    /// * 0: `rotate_screen`
    /// * 1: `reduce_flashing`
    /// * 2: `contrast`
    /// * 3: `easter_eggs`
    pub flags: u8,
}

// TODO: drop Copy.
#[derive(Copy, Clone, Serialize, Deserialize)]
pub(crate) struct FrameState {
    pub frame: u32,
    pub input: Input,
    pub extra: Extra,
}

/// Extra info for the frame.
///
/// Contains states that can be deterministically interpolated
/// and hence don't need to be synced on every frame.
#[derive(Copy, Clone, Serialize, Deserialize)]
pub(crate) enum Extra {
    /// The true RNG seed generated by the peer.
    Rand(u32),
    /// The current hardware time in microseconds.
    Now(u32),
    None,
    // TODO: RandKey.
}

#[derive(Clone, Serialize, Deserialize)]
pub(crate) struct Start {
    /// The full ID of the app to run.
    pub id: FullID,
    /// The peer's progress for each badge.
    pub badges: Box<[u16]>,
    /// The peer's top score for each board.
    pub scores: Box<[i16]>,
    /// The peer's stash, shared state preserved across games.
    pub stash: Box<[u8]>,
    /// The random seed to be used at the app startup.
    pub seed: u32,
}

#[derive(Copy, Clone, Serialize, Deserialize)]
pub(crate) struct Input {
    pub pad: Option<(i16, i16)>,
    pub buttons: u8,
}

impl From<Input> for InputState {
    fn from(value: Input) -> Self {
        Self {
            pad: value.pad.map(Into::into),
            buttons: value.buttons,
        }
    }
}
