use crate::error::HostError;
use crate::net::{FSPeer, Intro};
use crate::state::{NetHandler, State};
use alloc::boxed::Box;
use alloc::vec::Vec;
use firefly_hal::{Device, Network};

type C<'a, 'b> = wasmi::Caller<'a, Box<State<'b>>>;

/// Write a debug log message into console.
pub(crate) fn log_debug(mut caller: C, ptr: u32, len: u32) {
    let state = caller.data_mut();
    state.called = "misc.log_debug";
    let Some(memory) = state.memory else {
        state.log_error(HostError::MemoryNotFound);
        return;
    };
    let (data, state) = memory.data_and_store_mut(&mut caller);
    let ptr = ptr as usize;
    let len = len as usize;
    let Some(bytes) = &data.get(ptr..(ptr + len)) else {
        state.log_error(HostError::OomPointer);
        return;
    };
    let Ok(text) = core::str::from_utf8(bytes) else {
        state.log_error(HostError::TextUtf8);
        return;
    };
    state.device.log_debug("misc.log_debug", text);
    _ = state.save_log("debug", text);
}

/// Write a error log message into console.
pub(crate) fn log_error(mut caller: C, ptr: u32, len: u32) {
    let state = caller.data_mut();
    state.called = "misc.log_error";
    let Some(memory) = state.memory else {
        state.log_error(HostError::MemoryNotFound);
        return;
    };
    let (data, state) = memory.data_and_store_mut(&mut caller);
    let ptr = ptr as usize;
    let len = len as usize;
    let Some(bytes) = &data.get(ptr..(ptr + len)) else {
        state.log_error(HostError::OomPointer);
        return;
    };
    let Ok(text) = core::str::from_utf8(bytes) else {
        state.log_error(HostError::TextUtf8);
        return;
    };
    state.device.log_error("app", text);
}

/// Set random numbers generator seed.
pub(crate) fn set_seed(mut caller: C, seed: u32) {
    let state = caller.data_mut();
    state.called = "misc.set_seed";
    state.seed = seed;
    state.lock_seed = true;
}

/// Get a pseudo-random integer.
///
/// Uses [xorshift] algorithm. It's very fast, easy to implement,
/// and has a very long period. Wikipedia claims that it fails some
/// statistical tests, but that still should be good enough for games.
///
/// [xorshift]: https://en.wikipedia.org/wiki/Xorshift
pub(crate) fn get_random(mut caller: C) -> u32 {
    let state = caller.data_mut();
    state.called = "misc.get_random";

    // Use true RNG if no seed set by the app and it's not a multiplayer.
    let handler = state.net_handler.get_mut();
    if !state.lock_seed && matches!(handler, NetHandler::None) {
        return state.device.random();
    }

    let mut x = state.seed;
    if x == 0 {
        x = 1;
    }
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    state.seed = x;
    x
}

/// Get the name of the given peer device.
///
/// The buffer must be at least 16 bytes. Returns how many bytes are written.
///
/// The name should be valid and generated by firefly-cli when bootstrapping the FS.
/// If the name is missed or invalid, the buffer is untouched and 0 is returned.
pub(crate) fn get_name(mut caller: C, index: u32, ptr: u32) -> u32 {
    let state = caller.data_mut();
    state.called = "misc.get_name";
    let Some(memory) = state.memory else {
        state.log_error(HostError::MemoryNotFound);
        return 0;
    };
    let (data, state) = memory.data_and_store_mut(&mut caller);

    let handler = state.net_handler.get_mut();
    let name: &str = match handler {
        NetHandler::FrameSyncer(syncer) => {
            let Some(peer) = syncer.peers.get(index as usize) else {
                state.log_error("invalid peer ID");
                return 0;
            };
            &peer.intro.name
        }
        NetHandler::None => &state.settings.name,
        NetHandler::Connector(connector) => {
            if index == 0 {
                &connector.me.name
            } else {
                let index = index as usize - 1;
                match connector.peer_infos.get(index) {
                    Some(peer) => &peer.intro.name,
                    None => return 0,
                }
            }
        }
        NetHandler::Connection(connection) => {
            let Some(peer) = connection.peers.get(index as usize) else {
                return 0;
            };
            &peer.intro.name
        }
    };

    if name.is_empty() {
        return 0;
    }
    let ptr = ptr as usize;
    let len = name.len().min(16);
    let Some(buf) = data.get_mut(ptr..(ptr + len)) else {
        state.log_error(HostError::OomPointer);
        return 0;
    };
    buf.copy_from_slice(name.as_bytes());
    name.len() as u32
}

/// Get packed (some) system settings of the peer.
///
/// Contains interface language, color theme, and some boolean flags.
pub(crate) fn get_settings(mut caller: C, index: u32) -> u64 {
    let state = caller.data_mut();
    state.called = "misc.get_settings";

    let handler = state.net_handler.get_mut();
    match handler {
        NetHandler::FrameSyncer(syncer) => {
            if index > 32 {
                return combine_intros(&syncer.peers[..]);
            }
            let Some(peer) = syncer.peers.get(index as usize) else {
                state.log_error("invalid peer ID");
                return 0;
            };
            pack_intro(&peer.intro)
        }
        NetHandler::None => {
            let s = &state.settings;
            let flags = u8::from(s.rotate_screen)
                | u8::from(s.reduce_flashing) << 1
                | u8::from(s.contrast) << 2
                | u8::from(s.easter_eggs) << 3;
            pack_settings(s.theme, flags, s.lang)
        }
        NetHandler::Connector(connector) => {
            if index == 0 {
                pack_intro(&connector.me)
            } else {
                let index = index as usize - 1;
                match connector.peer_infos.get(index) {
                    Some(peer) => pack_intro(&peer.intro),
                    None => 0,
                }
            }
        }
        NetHandler::Connection(connection) => {
            let Some(peer) = connection.peers.get(index as usize) else {
                return 0;
            };
            pack_intro(&peer.intro)
        }
    }
}

/// Combine and serialize settings from intros of all peers.
///
/// Theme is the peers' theme if all peers have the same theme.
/// Otherwise, the default theme is used. The same is for language.
///
/// For boolean flags, the flag is set to true if any peer has it set to true.
/// So, for example, if a peer has high contrast set to true,
/// high contrast will be used for all peers.
///
/// Keep in mind that this is only used if the app requests `combined`
/// settings. The app can and should request and correctly handle settings
/// for `me` instead. Which, however, poses the challenge of avoiding the state drift.
/// So, combined settings might be preferred when the app wants to get the same
/// settings on all devices.
fn combine_intros(peers: &[FSPeer]) -> u64 {
    let default_theme = firefly_types::Settings::default().theme;
    let first = &peers[0].intro;
    let mut theme = first.theme;
    let mut flags = 0;
    let mut lang = first.lang;
    for peer in peers {
        flags |= peer.intro.flags;
        if peer.intro.lang != lang {
            lang = [b'e', b'n'];
        }
        if peer.intro.theme != theme {
            theme = default_theme;
        }
    }
    pack_settings(theme, flags, lang)
}

/// Pack settings from peer intro into 64 bits.
#[inline]
fn pack_intro(intro: &Intro) -> u64 {
    pack_settings(intro.theme, intro.flags, intro.lang)
}

/// Pack settings into 64 bits.
fn pack_settings(theme: u32, flags: u8, lang: [u8; 2]) -> u64 {
    let lang = u64::from(lang[0]) << 8 | u64::from(lang[1]);
    let flags = u64::from(flags);
    let theme = u64::from(theme);
    theme << 32 | flags << 16 | lang
}

/// Stop the currently running app and run the default launcher instead.
pub(crate) fn quit(mut caller: C) {
    let state = caller.data_mut();
    state.called = "misc.quit";
    let state = caller.data_mut();
    state.set_next(None);
}

/// Stop the currently running app and start it again.
pub(crate) fn restart(mut caller: C) {
    let state = caller.data_mut();
    state.called = "misc.restart";
    let state = caller.data_mut();
    state.set_next(Some(state.id.clone()));
}

/// Undocumented function called from `sys.connector` in `before_exit`.
///
/// Sets the mapping of the peers that the user accepted
/// and transitions net state from Connector into Connection.
/// If none of the peers are accepted, transitions into None (offline) instead.
///
/// It doesn't need to be sudo because it only works in the `Connector` state
/// which is only available when `sys.connector` is running.
/// Curiously enough, `sys.connector` is not a `sudo` app.
pub(crate) fn set_peers(mut caller: C, peer_map: u32) {
    let state = caller.data_mut();
    state.called = "misc.set_peers";
    let handler = state.net_handler.replace(NetHandler::None);
    let NetHandler::Connector(mut connector) = handler else {
        state.net_handler.replace(handler);
        state.log_error("can set connection status only for connector");
        return;
    };

    // TODO: do this in a single loop and without Vec.
    let mut to_remove: Vec<usize> = Vec::new();
    let mut peer_map = peer_map;
    for i in 0..connector.peer_infos.len() {
        if peer_map & 1 == 0 {
            to_remove.push(i);
        }
        peer_map >>= 1;
    }
    if !to_remove.is_empty() {
        to_remove.reverse();
        for i in to_remove {
            let res = connector.send_disconnect_to(&mut state.device, i);
            if let Err(err) = res {
                state.device.log_error("netcode", err);
            }
            connector.peer_infos.remove(i);
        }
        // If we sent disconnect to some peers and there are no more peers left
        // (which will make us disable networking below), wait a bit to make sure
        // the disconnect messages are delivered before we turn off wifi.
        if connector.peer_infos.is_empty() {
            state.device.delay(firefly_hal::Duration::from_ms(50));
        }
    }

    if connector.peer_infos.is_empty() {
        state.set_next(None);
        state.net_handler.replace(NetHandler::None);
        let res = state.device.net_stop();
        if let Err(err) = res {
            state.device.log_error("netcode", err);
        }
        return;
    }

    if let Err(err) = connector.validate() {
        state.device.log_error("netcode", err);
    }
    state.set_next(None);
    let connection = connector.finalize(&mut state.device);
    state
        .net_handler
        .replace(NetHandler::Connection(connection));
}
